language: node_js
sudo: false
node_js:
  - '4'

script:
  - make test-cov
  - ./node_modules/jshint/bin/jshint food_modules lib

after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1
